basePath: /v0
definitions:
  inputs.ChargeCode:
    properties:
      expiration_date:
        type: string
      max_capacity:
        type: integer
      name:
        type: string
      value:
        type: integer
    type: object
  models.Response:
    properties:
      data:
        type: object
      message:
        type: string
      status:
        type: string
    type: object
info:
  contact:
    email: fiber@swagger.io
    name: API Support
  description: I have no specific description
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Code API
  version: "1.0"
paths:
  /charge:
    post:
      description: create charge
      operationId: create_charge
      parameters:
      - description: charge code info
        in: body
        name: charge_code
        required: true
        schema:
          $ref: '#/definitions/inputs.ChargeCode'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Response'
        "400":
          description: Bad Request
          schema:
            type: json
      summary: create charge
      tags:
      - Charge
  /charge/{charge_code}:
    get:
      description: get charge
      operationId: get_charge
      parameters:
      - description: charge code name
        in: path
        name: charge_code
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Response'
        "400":
          description: Bad Request
          schema:
            type: json
      summary: get charge
      tags:
      - Charge
  /charge/{charge_code}/apply:
    post:
      description: charge code
      operationId: charge
      parameters:
      - description: charge code name
        in: path
        name: charge_code
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Response'
        "400":
          description: Bad Request
          schema:
            type: json
      summary: charge
      tags:
      - Charge
  /charge/{charge_code}/rollback:
    post:
      description: charge rollback
      operationId: charge_rollback
      parameters:
      - description: charge code name
        in: path
        name: charge_code
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Response'
        "400":
          description: Bad Request
          schema:
            type: json
      summary: charge
      tags:
      - Charge
swagger: "2.0"
